services:
  postgres:
    build:
      context: ./db 
      dockerfile: Dockerfile
    container_name: jem_assement_db
    environment:
      POSTGRES_USER: jemUser
      POSTGRES_PASSWORD: jemUser123
      POSTGRES_DB: jem_assessment_poc
    ports:
      - "5432:5432"
    networks:
      - my_network

  redis:
    image: "redis:latest"
    container_name: jem_assessment_redis
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis_volume_data:/data

  pyapp:
    container_name: pyapp
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgres
    networks:
      - my_network

  jem_celery_worker:
    container_name: jem_celery_worker
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - pyapp

volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  my_network:
    driver: bridge
